services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile Multi-stage
      target: app_prod
    container_name: laravel_date_app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - laravel_date_network      # Red interna existente
      - shared_services_network    # Red compartida con MySQL
    env_file:
      - .env
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web_prod
    container_name: laravel_date_web
    ports:
      - "8004:80"
    networks:
      - laravel_date_network
    depends_on:
      - app
    restart: always

# Definición de redes
networks:
  laravel_date_network:
    driver: bridge
  shared_services_network:
    external: true
    name: shared_services_network
